# Generated by Django 6.0.3 on 2026-03-15 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('rubro_empresa', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copropasitologico', models.CharField(max_length=100)),
                ('frotis_faringeo', models.CharField(max_length=100)),
                ('vdr_chagas', models.CharField(max_length=100)),
                ('fecha_examen', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_carnets.beneficiario')),
            ],
        ),
    ]
