# Generated by Django 6.0.3 on 2026-03-15 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_carnets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(max_length=20)),
                ('peso_kg', models.FloatField()),
                ('talla_cm', models.IntegerField()),
                ('observaciones_medicas', models.TextField(blank=True)),
                ('apto_para_carnet', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_carnets.beneficiario')),
            ],
        ),
    ]
