# Generated by Django 6.0.3 on 2026-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_carnets', '0002_evaluacionmedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20, null=True),
        ),
    ]
